/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteComboRouteImport } from './routes/_site.combo'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteOrderSuccessRouteImport } from './routes/_site.order-success'
import { Route as SiteShopRouteImport } from './routes/_site.shop'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SiteNewArrivalIdRouteImport } from './routes/_site.new-arrival.$id'
import { Route as SiteProductIdRouteImport } from './routes/_site.product.$id'
import { Route as SiteStartCollectingIdRouteImport } from './routes/_site.start-collecting.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteComboRoute = SiteComboRouteImport.update({
  id: '/combo',
  path: '/combo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderSuccessRoute = SiteOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteNewArrivalIdRoute = SiteNewArrivalIdRouteImport.update({
  id: '/new-arrival/$id',
  path: '/new-arrival/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductIdRoute = SiteProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStartCollectingIdRoute = SiteStartCollectingIdRouteImport.update({
  id: '/start-collecting/$id',
  path: '/start-collecting/$id',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/combo': typeof SiteComboRoute
  '/contact': typeof SiteContactRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/new-arrival/$id': typeof SiteNewArrivalIdRoute
  '/product/$id': typeof SiteProductIdRoute
  '/start-collecting/$id': typeof SiteStartCollectingIdRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/combo': typeof SiteComboRoute
  '/contact': typeof SiteContactRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/new-arrival/$id': typeof SiteNewArrivalIdRoute
  '/product/$id': typeof SiteProductIdRoute
  '/start-collecting/$id': typeof SiteStartCollectingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/combo': typeof SiteComboRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/order-success': typeof SiteOrderSuccessRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/new-arrival/$id': typeof SiteNewArrivalIdRoute
  '/_site/product/$id': typeof SiteProductIdRoute
  '/_site/start-collecting/$id': typeof SiteStartCollectingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/combo'
    | '/contact'
    | '/order-success'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/new-arrival/$id'
    | '/product/$id'
    | '/start-collecting/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/combo'
    | '/contact'
    | '/order-success'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/'
    | '/admin'
    | '/new-arrival/$id'
    | '/product/$id'
    | '/start-collecting/$id'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/cart'
    | '/_site/combo'
    | '/_site/contact'
    | '/_site/order-success'
    | '/_site/shop'
    | '/_site/terms'
    | '/admin/login'
    | '/_site/'
    | '/admin/'
    | '/_site/new-arrival/$id'
    | '/_site/product/$id'
    | '/_site/start-collecting/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/combo': {
      id: '/_site/combo'
      path: '/combo'
      fullPath: '/combo'
      preLoaderRoute: typeof SiteComboRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order-success': {
      id: '/_site/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof SiteOrderSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/new-arrival/$id': {
      id: '/_site/new-arrival/$id'
      path: '/new-arrival/$id'
      fullPath: '/new-arrival/$id'
      preLoaderRoute: typeof SiteNewArrivalIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$id': {
      id: '/_site/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SiteProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/start-collecting/$id': {
      id: '/_site/start-collecting/$id'
      path: '/start-collecting/$id'
      fullPath: '/start-collecting/$id'
      preLoaderRoute: typeof SiteStartCollectingIdRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteComboRoute: typeof SiteComboRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteOrderSuccessRoute: typeof SiteOrderSuccessRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteNewArrivalIdRoute: typeof SiteNewArrivalIdRoute
  SiteProductIdRoute: typeof SiteProductIdRoute
  SiteStartCollectingIdRoute: typeof SiteStartCollectingIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCartRoute: SiteCartRoute,
  SiteComboRoute: SiteComboRoute,
  SiteContactRoute: SiteContactRoute,
  SiteOrderSuccessRoute: SiteOrderSuccessRoute,
  SiteShopRoute: SiteShopRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteNewArrivalIdRoute: SiteNewArrivalIdRoute,
  SiteProductIdRoute: SiteProductIdRoute,
  SiteStartCollectingIdRoute: SiteStartCollectingIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
